FROM gradle:jdk21
WORKDIR /app
COPY build.gradle settings.gradle ./
COPY src ./src
RUN gradle clean bootJar -x test --no-daemon
EXPOSE 8080
CMD ["java", "-jar", "build/libs/backend-0.0.1-SNAPSHOT.jar"]